<?php

/**
 * Aplicação XPTO Swagger 
 * Exemplo de aplicação server-side utilizano o domínio de usuario como referência.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: atendimento@basis.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class AutenticaoApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation autenticar
     *
     * Obtém as informações do usuário.
     *
     *
     * @return Http response
     */
    public function autenticar()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['no_cpf'])) {
            throw new \InvalidArgumentException('Missing the required parameter $no_cpf when calling autenticar');
        }
        $no_cpf = $input['no_cpf'];

        if (!isset($input['ds_senha'])) {
            throw new \InvalidArgumentException('Missing the required parameter $ds_senha when calling autenticar');
        }
        $ds_senha = $input['ds_senha'];


        return response('How about implementing autenticar as a post method ?');
    }
    /**
     * Operation logoff
     *
     * Remove a autenticação do usuário logado.
     *
     *
     * @return Http response
     */
    public function logoff()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing logoff as a get method ?');
    }
}
